/*
 * Copyright (C) 2019 Spazio IT - Soluzioni Informatiche.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with This program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 * 
 * This work has been funded by the European Space Agency
 * Contract # RFP/3-15558/18/NL/FE/as 
 */
package com.spazioit.safacilitator.functions;

import com.spazioit.safacilitator.SAFacilitator;
import com.spazioit.safacilitator.gui.MainFrame;
import com.spazioit.safacilitator.model.Project;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Calendar;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Maurizio Martignano
 */
public class SonarQubeFunctions {
    
    private SAFacilitator safacilitator = null;
    private Executor executor = null;
    
    private String PCLINT_REP_PATH="pclint-reports/pclint-result-*.xml";
    private String CPPCHECK_REP_PATH="cppcheck-reports/cppcheck-result-*.xml";
    private String CLANGSA_REP_PATH="clangsa/*plist";
    private String CLANGTIDY_REP_PATH="clangtidy-reports/clangtidy-result-*.txt";
    private String COMP_REP_PATH="comp-reports/comp-result-*.txt";

    private String EXPLODED = "_EXPLODED";

    
    public SonarQubeFunctions(SAFacilitator safacilitator) {
        this.safacilitator = safacilitator;
    }

    /**
     * @throws Exception in case of application error
     * prepare SonarQube
     */
    public void prepareSonarQube() throws Exception {
        CommonFunctions.printLogMessage("Preparing SonarQube...");
        Project p = safacilitator.currentProject;
        if (p == null) {
            throw new Exception("Current Project is null. Initialize it first!");
        }
        if (p.getProjectName() == null || p.getProjectName().equals("")) {
           throw new Exception("Project name cannot be null. Initialize it first!");
        }
        if (p.getProjectKey() == null || p.getProjectKey().equals("")) {
           throw new Exception("Project key cannot be null. Initialize it first!");
        }
        if (p.getProjectVersion() == null || p.getProjectVersion().equals("")) {
           throw new Exception("Project version cannot be null. Initialize it first!");
        }
        if (p.getSonarQubeUrl() == null || p.getSonarQubeUrl().equals("")) {
           throw new Exception("SonarQube URL cannot be null. Initialize it first!");
        }
        if (p.getSonarQubeUrl() == null || p.getSonarQubeUrl().equals("")) {
           throw new Exception("SonarQube URL cannot be null. Initialize it first!");
        }
        if (p.getSonarScanner() == null || p.getSonarScanner().equals("")) {
           throw new Exception("SonarScanner command cannot be null. Initialize it first!");
        }
        String fileName =  null;
        if (!p.getPreProcessingEnabled()) {
            fileName = p.getBaseDirectory() + "/sonar-project.properties";
        } else {
            fileName = p.getExplodedDirectory() + "/sonar-project.properties";
        }
        FileWriter fw = new FileWriter(fileName);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write("#  SonarQube configuration file for project " + p.getProjectName());
        bw.newLine();
        bw.write("#  Generated by SAFacilitator at "  + Calendar.getInstance().getTime()); 
        bw.newLine();
        bw.write("#  Copyright (C) " + Calendar.getInstance().get(Calendar.YEAR) +  " - Spazio IT - https://www.spazioit.com");
        bw.newLine();
        bw.newLine();
        bw.write("#  Required metadata");
        bw.newLine();
        if (!p.getPreProcessingEnabled()) {
            bw.write("sonar.projectName=" + p.getProjectName());             
            bw.newLine();
            bw.write("sonar.projectKey=" + p.getProjectKey()); 
            bw.newLine();
            bw.write("sonar.projectVersion=" + p.getProjectVersion());
            bw.newLine();
        } else {
            bw.write("sonar.projectName=" + p.getProjectName() + EXPLODED);             
            bw.newLine();
            bw.write("sonar.projectKey=" + p.getProjectKey() + EXPLODED); 
            bw.newLine();
            bw.write("sonar.projectVersion=" + p.getProjectVersion() + EXPLODED);
            bw.newLine();
        }
        bw.newLine();
        bw.write("#  Default macros");
        bw.newLine();
        bw.write("sonar.cxx.defines=");
        for (int i = 0; i < p.getDefines().size(); i++) {
            bw.write(p.getDefines().get(i).substring(2));
            if (i < (p.getDefines().size() - 1)) {
                bw.write(",");
            }
        }
        bw.newLine();
        bw.newLine();
        bw.write("#  Source files information");
        bw.newLine();
        if (!p.getPreProcessingEnabled()) {
            bw.write("sonar.projectBaseDir=" + p.getBaseDirectory());
        } else {
            bw.write("sonar.projectBaseDir=" + p.getExplodedDirectory());
        }
        bw.newLine();
        bw.write("sonar.sources=");
        if (p.getSourceDirectories() == null || p.getSourceDirectories().size() == 0) {
            bw.write(".");
        } else {
            for (int i = 0; i < p.getSourceDirectories().size(); i++) {
                bw.write(p.getSourceDirectories().get(i));
                if (i < (p.getSourceDirectories().size() - 1)) {
                    bw.write(",");
                }
            }
        }
        bw.newLine();
        bw.write("sonar.cxx.includeDirectories=");
        for (int i = 0; i < p.getIncludeDirectories().size(); i++) {
            bw.write(p.getIncludeDirectories().get(i));
            if (i < (p.getIncludeDirectories().size() - 1)) {
                bw.write(",");
            }
        }
        bw.newLine();
        bw.newLine();
        bw.write("#  Report files information");
        bw.newLine();
        if (!p.getPreProcessingEnabled()) {
            bw.write("sonar.cxx.pclint.reportPath=" + p.getBaseDirectory() + "/" + PCLINT_REP_PATH);
            bw.newLine();
            bw.write("sonar.cxx.cppcheck.reportPath="  + p.getBaseDirectory() + "/" + CPPCHECK_REP_PATH);
            bw.newLine();
            bw.write("sonar.cxx.clangsa.reportPath="+ p.getBaseDirectory() + "/" + CLANGSA_REP_PATH);
            bw.newLine();
            bw.write("sonar.cxx.clangtidy.reportPath=" + p.getBaseDirectory() + "/" + CLANGTIDY_REP_PATH);
            bw.newLine();
            bw.write("sonar.cxx.compiler.reportPath=" + p.getBaseDirectory() + "/" + COMP_REP_PATH);
            bw.newLine();
        } else {
            /*
            bw.write("sonar.cxx.pclint.reportPath=" + p.getExplodedDirectory() + "/" + PCLINT_REP_PATH);
            bw.newLine();
            bw.write("sonar.cxx.cppcheck.reportPath="  + p.getExplodedDirectory() + "/" + CPPCHECK_REP_PATH);
            bw.newLine();
            */
            bw.write("sonar.cxx.clangsa.reportPath="+ p.getExplodedDirectory() + "/" + CLANGSA_REP_PATH);            
            bw.newLine();
            /*
            bw.write("sonar.cxx.clangtidy.reportPath=" + p.getExplodedDirectory() + "/" + CLANGTIDY_REP_PATH);
            bw.newLine();
            bw.write("sonar.cxx.compiler.reportPath=" + p.getExplodedDirectory() + "/" + COMP_REP_PATH);
            bw.newLine();
            */
        }
        bw.newLine();
        bw.write("#  Language information");
        bw.newLine();
        bw.write("sonar.language=c++");
        bw.newLine();
        bw.write("sonar.lang.patterns.c++ : **/*.c,**/*.c++,**/*.cc,**/*.cpp,**/*.cxx");
        bw.newLine();
        bw.write("sonar.lang.patterns.c : **/*.x");
        bw.newLine();
        bw.write("sonar.cxx.compiler.parser=GCC");
        bw.newLine();
        bw.newLine();
        bw.write("#  Sonar URL and login");
        bw.newLine();
        bw.write("sonar.host.url=" + p.getSonarQubeUrl());
        bw.newLine();
        if ((p.getSonarQubeUserName()) != null && (!p.getSonarQubeUserName().equals(""))) {
            bw.write("sonar.login=" + p.getSonarQubeUserName());
            bw.newLine();            
        }
        if ((p.getSonarQubeUserPassword()) != null && (!p.getSonarQubeUserPassword().equals(""))) {
            bw.write("sonar.password=" + p.getSonarQubeUserPassword());
            bw.newLine();            
        }
        bw.newLine();
        bw.flush();
        bw.close();
        if (System.getProperty("os.name").toLowerCase().startsWith("windows")) {
            if (!p.getPreProcessingEnabled()) {
                fileName = p.getBaseDirectory() + "/run_sonar.bat";
            } else {
                fileName = p.getExplodedDirectory() + "/run_sonar.bat";
            }
            fw = new FileWriter(fileName);
            bw = new BufferedWriter(fw);
            bw.write("@echo off");
            bw.newLine();
            bw.write("REM  SonarScanner launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write("REM  Generated by SAFacilitator at "  + Calendar.getInstance().getTime()); 
            bw.newLine();
            bw.write("REM  Copyright (C) " + Calendar.getInstance().get(Calendar.YEAR) +  " - Spazio IT - https://www.spazioit.com");
            bw.newLine();
            bw.newLine();
            if (!p.getPreProcessingEnabled()) {
                bw.write("cd " + p.getBaseDirectory());
            } else {
                bw.write("cd " + p.getExplodedDirectory());                
            }
            bw.newLine();
            bw.write(p.getSonarScanner());
            bw.newLine();
        } else {
            if (!p.getPreProcessingEnabled()) {
                fileName = p.getBaseDirectory() + "/run_sonar.sh";
            } else {
                fileName = p.getExplodedDirectory() + "/run_sonar.sh";
            }
            fw = new FileWriter(fileName);
            bw = new BufferedWriter(fw);
            bw.write("# !/bin/bash");
            bw.newLine();
            bw.write("#  SonarScanner launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write("#  Generated by SAFacilitator at "  + Calendar.getInstance().getTime()); 
            bw.newLine();
            bw.write("#  Copyright (C) " + Calendar.getInstance().get(Calendar.YEAR) +  " - Spazio IT - https://www.spazioit.com");
            bw.newLine();
            bw.newLine();
            if (!p.getPreProcessingEnabled()) {
                bw.write("cd " + p.getBaseDirectory());
            } else {
                bw.write("cd " + p.getExplodedDirectory());                
            }
            bw.newLine();
            bw.write(p.getSonarScanner());
            bw.newLine();
        }
        bw.newLine();
        bw.flush();
        bw.close();
       CommonFunctions.printLogMessage("SonarQube prepared.");        
    }
    
    /**
     * @throws Exception in case of application error
     * run SonarScanner
     */
    public void runSonarScanner() throws Exception {
        CommonFunctions.printLogMessage("Running SonarScanner...");
        Project p = safacilitator.currentProject;
        if (p == null) {
            throw new Exception("Current Project is null. Initialize it first!");
        }
        String commandLine = null;
        if (System.getProperty("os.name").toLowerCase().startsWith("windows")) {
            if (!p.getPreProcessingEnabled()) {
                commandLine = p.getBaseDirectory() + "/run_sonar.bat";
            } else {
                commandLine = p.getExplodedDirectory() + "/run_sonar.bat";
            }
        } else {
            if (!p.getPreProcessingEnabled()) {
                commandLine = "bash " + p.getBaseDirectory() + "/run_sonar.sh";
            } else {
                commandLine = "bash " + p.getExplodedDirectory() + "/run_sonar.sh";
            }
        }
        if (SAFacilitator.guiEnabled) {
            MainFrame.stopRunningMenuItem.setText("Stop SonarScanner");
            MainFrame.stopRunningMenuItem.setDisable(false);
        }
        executor = new Executor(commandLine, "SonarScanner executed.", true);
        executor.setPriority(Thread.MAX_PRIORITY);
        executor.start();
        if (!SAFacilitator.guiEnabled) {
            executor.join();
        }
    }
    
}
