/*
 * Copyright (C) 2019 Spazio IT - Soluzioni Informatiche.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with This program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 * 
 * This work has been funded by the European Space Agency
 * Contract # RFP/3-15558/18/NL/FE/as 
 */
package com.spazioit.safacilitator.functions;

import com.spazioit.safacilitator.SAFacilitator;
import com.spazioit.safacilitator.Strings;
import com.spazioit.safacilitator.gui.MainFrame;
import com.spazioit.safacilitator.model.Project;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Maurizio Martignano
 */
@SuppressWarnings("unchecked")
public class AnalyzersFunctions {

    private SAFacilitator safacilitator = null;
    private Executor executor = null;

    private static final String PCLINT_OUT_DIR = "pclint-reports";
    private static final String PCLINT_OUT_REP_UNX = "pclint-reports/pclint-result-01.xml";
    private static final String PCLINT_OUT_REP_WIN = "pclint-reports\\pclint-result-01.xml";
    private static final String CPPCHECK_OUT_DIR = "cppcheck-reports";
    private static String cppcheckBuildDir = "";
    private static final String CPPCHECK_OUT_REP_UNX = "cppcheck-reports/cppcheck-result-01.xml";
    private static final String CPPCHECK_OUT_REP_WIN = "cppcheck-reports\\cppcheck-result-01.xml";
    private static final String CLANGSA_OUT_DIR = "clangsa";
    private static final String CLANGTIDY_OUT_DIR = "clangtidy-reports";
    private static final String CLANGTIDY_OUT_REP_UNX = "clangtidy-reports/clangtidy-result-01.txt";
    private static final String CLANGTIDY_OUT_REP_WIN = "clangtidy-reports\\clangtidy-result-01.txt";
    private static final String COMP_OUT_DIR = "comp-reports";
    private static final String COMP_OUT_REP_UNX = "comp-reports/comp-result-01.txt";
    private static final String COMP_OUT_REP_WIN = "comp-reports\\comp-result-01.txt";
    private static final String ECHO_OFF_WIN = "@echo off";
    private static final String GENERATED_BY_UNX = "#  Generated by SAFacilitator at ";
    private static final String GENERATED_BY_WIN = "REM  Generated by SAFacilitator at ";
    private static final String COPYRIGHT_UNX = "#  Copyright (C) ";
    private static final String COPYRIGHT_WIN = "REM  Copyright (C) ";
    private static final String BIN_BASH_UNX = "# !/bin/bash";
    private static final String CLANG_SA_SUFF_UNX = "_clang-sa.sh";
    private static final String CLANG_SA_SUFF_WIN = "_clang-sa.bat";
    private static final String CLANG_TIDY_SUFF_UNX = "_clang-tidy.sh";
    private static final String CLANG_TIDY_SUFF_WIN = "_clang-tidy.bat";

    public AnalyzersFunctions(SAFacilitator safacilitator) {
        this.safacilitator = safacilitator;
    }

    /**
     * @throws Exception in case of application error prepare the various
     * analyzers
     */
    public void prepareAnalyzers() throws Exception {
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        List<String> myList = p.getActiveAnalyzers();
        if (myList == null || myList.isEmpty()) {
            throw new Exception(Strings.ACTIVE_ANALYZERS_LIST_IS_EMPTY);
        }
        if (myList.contains(Strings.PC_LINT)) {
            if (!p.getPreProcessingEnabled()) {
                preparePcLint();
            }
        }
        if (myList.contains(Strings.CPPCHECK)) {
            if (!p.getPreProcessingEnabled()) {
                prepareCppcheck();
            }
        }
        if (myList.contains(Strings.CLANG_SA)) {
            prepareClangSa();
        }
        if (myList.contains(Strings.CLANG_TIDY)) {
            if (!p.getPreProcessingEnabled()) {
                prepareClangTidy();
            }
        }
        if (myList.contains(Strings.COMP)) {
            if (!p.getPreProcessingEnabled()) {
                prepareComp();
            }
        }

        prepareCompilationDatabase();
    }

    /**
     * @throws Exception in case of application error prepare Compilation
     * Database
     */
    void prepareCompilationDatabase() throws Exception {
        Project p = safacilitator.getCurrentProject();
        FileFunctions fileFunctions = new FileFunctions(safacilitator);
        CommonFunctions.printLogMessage("Preparing Compilation Database...");
        if (!p.getPreProcessingEnabled()) {
            fileFunctions.saveProjectAsCompileCommands(p.getBaseDirectory() + "/compile_commands.json");
        } else {
            fileFunctions.saveProjectAsCompileCommands(p.getExplodedDirectory() + "/compile_commands.json");
        }
        CommonFunctions.printLogMessage("Compilation Database prepared.");
    }

    /**
     * @throws Exception in case of application error prepare PC-Lint
     */
    void preparePcLint() throws Exception {
        CommonFunctions.printLogMessage("Preparing PC-Lint...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String fileName = p.getBaseDirectory() + "/" + p.getProjectName() + ".lnt";
        FileWriter fw = new FileWriter(fileName);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write("//  PC-lint configuration file for project " + p.getProjectName());
        bw.newLine();
        bw.write("//  Generated by SAFacilitator at " + LocalDateTime.now().format(SAFacilitator.getFormatter()));
        bw.newLine();
        bw.write("//  Copyright (C) " + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
        bw.newLine();
        bw.newLine();
        bw.write("//  Spazio IT recommendations and checks recommended by industry bodies");
        bw.newLine();
        bw.write("au-barr10.lnt");
        bw.newLine();
        bw.write("au-misra2.lnt");
        bw.newLine();
        bw.write("au-misra3.lnt");
        bw.newLine();
        bw.write("au-sm123.lnt");
        bw.newLine();
        bw.newLine();
        bw.write("// Compiler configuration");
        bw.newLine();
        bw.write("co-gcc.lnt");
        bw.newLine();
        bw.newLine();
        bw.write("//  PC-lint warning level (0 through 4)");
        bw.newLine();
        bw.write("-w3");
        bw.newLine();
        bw.newLine();
        bw.write("//  Spazio IT preferred PC-lint options");
        bw.newLine();
        bw.write("-e309 -e98 -e322 -e952 -e953 -e956 +fqb +e970");
        bw.newLine();
        bw.newLine();
        bw.write("//  Do not stop on error");
        bw.newLine();
        bw.write("+fce");
        bw.newLine();
        bw.newLine();
        bw.write("//  Defines");
        bw.newLine();
        for (int i = 0; i < p.getDefines().size(); i++) {
            bw.write(p.getDefines().get(i));
            bw.newLine();
        }
        bw.newLine();
        bw.write("//  Include Directories Files");
        bw.newLine();
        for (int i = 0; i < p.getIncludeDirectories().size(); i++) {
            if (p.getIncludeDirectories().get(i).startsWith("/")
                    || p.getIncludeDirectories().get(i).startsWith("C:")
                    || p.getIncludeDirectories().get(i).startsWith("c:")) {
                bw.write("-I" + p.getIncludeDirectories().get(i));
            } else {
                bw.write("-I" + p.getBaseDirectory() + "/" + p.getIncludeDirectories().get(i));
            }
            bw.newLine();
        }
        bw.newLine();
        bw.write("//  Generate XML");
        bw.newLine();
        bw.write("env-xml.lnt");
        bw.newLine();
        bw.newLine();
        bw.write("//  Source Files");
        bw.newLine();
        for (int i = 0; i < p.getpFiles().size(); i++) {
            bw.write(p.getpFiles().get(i).getPfFileName());
            bw.newLine();
        }
        bw.newLine();
        bw.flush();
        bw.close();
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            fileName = p.getBaseDirectory() + "/run_pclint.bat";
            fw = new FileWriter(fileName);
            bw = new BufferedWriter(fw);
            bw.write(ECHO_OFF_WIN);
            bw.newLine();
            bw.write("REM  PC-Lint launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_WIN + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_WIN + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("C:\\lint\\lint-nt.exe -IC:\\lint\\scripts " + p.getProjectName()
                    + ".lnt > " + PCLINT_OUT_REP_WIN);
            bw.newLine();
        } else {
            fileName = p.getBaseDirectory() + "/run_pclint.sh";
            fw = new FileWriter(fileName);
            bw = new BufferedWriter(fw);
            bw.write(BIN_BASH_UNX);
            bw.newLine();
            bw.write("#  PC-Lint launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_UNX + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_UNX + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("wine /opt/lint/lint-nt.exe -I/opt/lint/scripts " + p.getProjectName()
                    + ".lnt > " + PCLINT_OUT_REP_UNX);
            bw.newLine();
        }
        bw.newLine();
        bw.flush();
        bw.close();
        CommonFunctions.printLogMessage("PC-Lint prepared.");
    }

    /**
     * @throws Exception in case of application error prepare Cppcheck
     */
    void prepareCppcheck() throws Exception {
        CommonFunctions.printLogMessage("Preparing Cppcheck...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String fileName = p.getBaseDirectory() + "/" + p.getProjectName() + ".cppcheck";
        FileWriter fw = new FileWriter(fileName);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        bw.newLine();
        bw.write("<!-- Cppcheck configuration file for project " + p.getProjectName() + " -->");
        bw.newLine();
        bw.write("<!-- Generated by SAFacilitator at " + LocalDateTime.now().format(SAFacilitator.getFormatter()) + " -->");
        bw.newLine();
        bw.write("<!-- Copyright (C) " + LocalDate.now().getYear() + " - Spazio IT - https://www.spazioit.com -->");
        bw.newLine();
        bw.write("<project version=\"1\">");
        bw.newLine();
        cppcheckBuildDir = p.getProjectName() + "-cppcheck-build-dir";
        bw.write("    <builddir>" + cppcheckBuildDir + "</builddir>");
        bw.newLine();
        bw.write("    <platform>unix64</platform>");
        bw.newLine();
        bw.write("    <analyze-all-vs-configs>true</analyze-all-vs-configs>");
        bw.newLine();
        bw.write("    <includedir>");
        bw.newLine();
        for (int i = 0; i < p.getIncludeDirectories().size(); i++) {
            bw.write("        <dir name=\"" + p.getIncludeDirectories().get(i) + "\"/>");
            bw.newLine();
        }
        bw.write("    </includedir>");
        bw.newLine();
        List<String> myDef = new ArrayList<String>();
        List<String> myUndef = new ArrayList<String>();
        for (int i = 0; i < p.getDefines().size(); i++) {
            String define = p.getDefines().get(i);
            if (define != null && (!define.equals(""))) {
                if (define.startsWith("-D")) {
                    myDef.add(define.substring(2));
                } else {
                    myUndef.add(define.substring(2));
                }
            }
        }
        bw.write("    <defines>");
        bw.newLine();
        if (myDef.size() > 0) {
            for (int i = 0; i < myDef.size(); i++) {
                bw.write("        <define name=\"");
                bw.write(myDef.get(i).replace("\"", "&quot;"));
                bw.write("\"/>");
                bw.newLine();
            }
        }
        bw.write("    </defines>");
        bw.newLine();
        bw.write("    <undefines>");
        bw.newLine();
        if (myUndef.size() > 0) {
            for (int i = 0; i < myUndef.size(); i++) {
                bw.write("        <undefine name=\"");
                bw.write(myUndef.get(i).replace("\"", "&quot;"));
                bw.write("\"/>");
                bw.newLine();
            }
        }
        bw.write("    </undefines>");
        bw.newLine();
        bw.write("    <paths>");
        bw.newLine();
        for (int i = 0; i < p.getSourceDirectories().size(); i++) {
            if (p.getSourceDirectories().get(i).startsWith("/")
                    || p.getSourceDirectories().get(i).startsWith("C:")
                    || p.getSourceDirectories().get(i).startsWith("c:")) {
                bw.write("        <dir name=\"" + p.getSourceDirectories().get(i) + "\"/>");
            } else {
                bw.write("        <dir name=\"" + p.getBaseDirectory() + "/" + p.getSourceDirectories().get(i) + "\"/>");
            }
            bw.newLine();
        }
        bw.write("    </paths>");
        bw.newLine();
        bw.write("    <libraries>");
        bw.newLine();
        bw.write("        <library>gnu</library>");
        bw.newLine();
        bw.write("        <library>posix</library>");
        bw.newLine();
        bw.write("    </libraries>");
        bw.newLine();
        bw.write("    <addons>");
        bw.newLine();
        bw.write("        <addon>threadsafety</addon>");
        bw.newLine();
        bw.write("        <addon>y2038</addon>");
        bw.newLine();
        bw.write("        <addon>cert</addon>");
        bw.newLine();
        bw.write("    </addons>");
        bw.newLine();
        bw.write("</project>");
        bw.newLine();
        bw.newLine();
        bw.flush();
        bw.close();
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            fileName = p.getBaseDirectory() + "/run_cppcheck.bat";
            fw = new FileWriter(fileName);
            bw = new BufferedWriter(fw);
            bw.write(ECHO_OFF_WIN);
            bw.newLine();
            bw.write("REM  Cppcheck launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_WIN + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_WIN + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("\"C:\\Program Files\\Cppcheck\\cppcheck.exe\" --project=" + p.getProjectName()
                    + ".cppcheck --enable=all --xml --quiet --output-file=" + CPPCHECK_OUT_REP_WIN);
            bw.newLine();
        } else {
            fileName = p.getBaseDirectory() + "/run_cppcheck.sh";
            fw = new FileWriter(fileName);
            bw = new BufferedWriter(fw);
            bw.write(BIN_BASH_UNX);
            bw.newLine();
            bw.write("#  Cppcheck launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_UNX + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_UNX + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("cppcheck --project=" + p.getProjectName()
                    + ".cppcheck --enable=all --xml --quiet --output-file=" + CPPCHECK_OUT_REP_UNX);
            bw.newLine();
        }
        bw.newLine();
        bw.flush();
        bw.close();
        CommonFunctions.printLogMessage("Cppcheck prepared.");
    }

    /**
     * @throws Exception in case of application error prepare Clang-SA
     */
    void prepareClangSa() throws Exception {
        CommonFunctions.printLogMessage("Preparing Clang-SA...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            String fileName = null;
            if (!p.getPreProcessingEnabled()) {
                fileName = p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_WIN;
            } else {
                fileName = p.getExplodedDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_WIN;
            }
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(ECHO_OFF_WIN);
            bw.newLine();
            bw.write("REM  Clang-SA launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_WIN + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_WIN + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            if (!p.getPreProcessingEnabled()) {
                bw.write("cd " + p.getBaseDirectory());
            } else {
                bw.write("cd " + p.getExplodedDirectory());
            }
            bw.newLine();
            bw.write("echo Clang-SA running > Clang-SA.running");
            bw.newLine();
            for (int i = 0; i < p.getpFiles().size(); i++) {
                bw.write("if exist Clang-SA.running (");
                bw.newLine();
                bw.write("clang-check -analyze ");
                if (!p.getPreProcessingEnabled()) {
                    bw.write(p.getpFiles().get(i).getPfFileName() + " ");
                } else {
                    bw.write(p.getpFiles().get(i).getPfFileName().replace(p.getBaseDirectory(), p.getExplodedDirectory()) + " ");
                }
                for (int j = 0; j < p.getpFiles().get(i).getPfDefines().size(); j++) {
                    bw.write("-extra-arg-before=\"" + p.getpFiles().get(i).getPfDefines().get(j).replace("\"", "\\\"") + "\"");
                    bw.write(" ");
                }
                bw.write("-extra-arg-before=\"-ferror-limit=0\" ");
                for (int j = 0; j < p.getpFiles().get(i).getPfIncludeDirectories().size(); j++) {
                    if (p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("/")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("C:")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("c:")) {
                        bw.write("-extra-arg-before=\"-I" + p.getpFiles().get(i).getPfIncludeDirectories().get(j) + "\"");
                    } else {
                        bw.write("-extra-arg-before=\"-I" + p.getBaseDirectory() + "/" + p.getpFiles().get(i).getPfIncludeDirectories().get(j) + "\"");
                    }
                    bw.write(" ");
                }
                bw.newLine();
                bw.write(")");
                bw.newLine();
            }
            bw.write("del /F /Q Clang-SA.running");
            bw.newLine();
            bw.newLine();
            bw.flush();
            bw.close();
        } else {
            String fileName = null;
            if (!p.getPreProcessingEnabled()) {
                fileName = p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_UNX;
            } else {
                fileName = p.getExplodedDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_UNX;
            }
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(BIN_BASH_UNX);
            bw.newLine();
            bw.write("#  Clang-SA launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_UNX + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_UNX + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            if (!p.getPreProcessingEnabled()) {
                bw.write("cd " + p.getBaseDirectory());
            } else {
                bw.write("cd " + p.getExplodedDirectory());
            }
            bw.newLine();
            bw.write("echo Clang-SA running > Clang-SA.running");
            bw.newLine();
            for (int i = 0; i < p.getpFiles().size(); i++) {
                bw.write("if [ -f Clang-SA.running ]; then");
                bw.newLine();
                bw.write("clang-check -analyze ");
                if (!p.getPreProcessingEnabled()) {
                    bw.write(p.getpFiles().get(i).getPfFileName() + " ");
                } else {
                    bw.write(p.getpFiles().get(i).getPfFileName().replace(p.getBaseDirectory(), p.getExplodedDirectory()) + " ");
                }
                for (int j = 0; j < p.getpFiles().get(i).getPfDefines().size(); j++) {
                    bw.write("-extra-arg-before=\"" + p.getpFiles().get(i).getPfDefines().get(j).replace("\"", "\\\"") + "\"");
                    bw.write(" ");
                }
                bw.write("-extra-arg-before=\"-ferror-limit=0\" ");
                for (int j = 0; j < p.getpFiles().get(i).getPfIncludeDirectories().size(); j++) {
                    if (p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("/")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("C:")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("c:")) {
                        bw.write("-extra-arg-before=\"-I" + p.getpFiles().get(i).getPfIncludeDirectories().get(j) + "\"");
                    } else {
                        bw.write("-extra-arg-before=\"-I" + p.getBaseDirectory() + "/" + p.getpFiles().get(i).getPfIncludeDirectories().get(j) + "\"");
                    }
                    bw.write(" ");
                }
                bw.newLine();
                bw.write("fi");
                bw.newLine();
            }
            bw.write("rm -f Clang-SA.running");
            bw.newLine();
            bw.newLine();
            bw.flush();
            bw.close();
        }
        CommonFunctions.printLogMessage("Clang-SA prepared.");
    }

    /**
     * @throws Exception in case of application error prepare Clang-Tidy
     */
    void prepareClangTidy() throws Exception {
        CommonFunctions.printLogMessage("Preparing Clang-Tidy...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            String fileName = p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_TIDY_SUFF_WIN;
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(ECHO_OFF_WIN);
            bw.newLine();
            bw.write("REM  Clang-Tidy launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_WIN + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_WIN + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("del /F /Q " + CLANGTIDY_OUT_REP_WIN);
            bw.newLine();
            bw.write("echo Clang-Tidy running > Clang-Tidy.running");
            bw.newLine();
            for (int i = 0; i < p.getpFiles().size(); i++) {
                bw.write("if exist Clang-Tidy.running (");
                bw.newLine();
                bw.write("clang-tidy -checks=*,cert-*,clang-analyzer-*,cppcoreguidelines-*,hicpp-* ");
                bw.write(p.getpFiles().get(i).getPfFileName() + " -- ");
                for (int j = 0; j < p.getpFiles().get(i).getPfDefines().size(); j++) {
                    bw.write(p.getpFiles().get(i).getPfDefines().get(j).replace("\"", "\\\""));
                    bw.write(" ");
                }
                bw.write("-ferror-limit=0 ");
                for (int j = 0; j < p.getpFiles().get(i).getPfIncludeDirectories().size(); j++) {
                    if (p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("/")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("C:")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("c:")) {
                        bw.write("-I" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    } else {
                        bw.write("-I" + p.getBaseDirectory() + "/" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    }
                    bw.write(" ");
                }
                bw.write(">> " + CLANGTIDY_OUT_REP_WIN);
                bw.newLine();
                bw.write(")");
                bw.newLine();
            }
            bw.write("del /F /Q Clang-Tidy.running");
            bw.newLine();
            bw.newLine();
            bw.flush();
            bw.close();
        } else {
            String fileName = p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_TIDY_SUFF_UNX;
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(BIN_BASH_UNX);
            bw.newLine();
            bw.write("#  Clang-Tidy launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_UNX + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_UNX + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("rm -f " + CLANGTIDY_OUT_REP_UNX);
            bw.newLine();
            bw.write("echo Clang-Tidy running > Clang-Tidy.running");
            bw.newLine();
            for (int i = 0; i < p.getpFiles().size(); i++) {
                bw.write("if [ -f Clang-Tidy.running ]; then");
                bw.newLine();
                bw.write("clang-tidy -checks=*,cert-*,clang-analyzer-*,cppcoreguidelines-*,hicpp-* ");
                bw.write(p.getpFiles().get(i).getPfFileName() + " -- ");
                for (int j = 0; j < p.getpFiles().get(i).getPfDefines().size(); j++) {
                    bw.write(p.getpFiles().get(i).getPfDefines().get(j).replace("\"", "\\\""));
                    bw.write(" ");
                }
                bw.write("-ferror-limit=0 ");
                for (int j = 0; j < p.getpFiles().get(i).getPfIncludeDirectories().size(); j++) {
                    if (p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("/")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("C:")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("c:")) {
                        bw.write("-I" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    } else {
                        bw.write("-I" + p.getBaseDirectory() + "/" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    }
                    bw.write(" ");
                }
                bw.write(">> " + CLANGTIDY_OUT_REP_UNX);
                bw.newLine();
                bw.write("fi");
                bw.newLine();
            }
            bw.write("rm -f Clang-Tidy.running");
            bw.newLine();
            bw.newLine();
            bw.flush();
            bw.close();
        }
        CommonFunctions.printLogMessage("Clang-Tidy prepared.");
    }

    /**
     * @throws Exception in case of application error prepare COMP
     */
    void prepareComp() throws Exception {
        CommonFunctions.printLogMessage("Preparing COMP...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            String fileName = p.getBaseDirectory() + "/" + p.getProjectName() + "_comp.bat";
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(ECHO_OFF_WIN);
            bw.newLine();
            bw.write("REM  COMP launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_WIN + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_WIN + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("del /F /Q " + COMP_OUT_REP_WIN);
            bw.newLine();
            bw.write("echo COMP running > COMP.running");
            bw.newLine();
            for (int i = 0; i < p.getpFiles().size(); i++) {
                bw.write("if exist COMP.running (");
                bw.newLine();
                bw.write(p.getpFiles().get(i).getPfOriginalBuilder() + " ");
                for (int j = 0; j < p.getpFiles().get(i).getPfDefines().size(); j++) {
                    bw.write(p.getpFiles().get(i).getPfDefines().get(j).replace("\"", "\\\""));
                    bw.write(" ");
                }
                for (int j = 0; j < p.getpFiles().get(i).getPfAdditionalArguments().size(); j++) {
                    bw.write(p.getpFiles().get(i).getPfAdditionalArguments().get(j).replace("\"", "\\\""));
                    bw.write(" ");
                }
                for (int j = 0; j < p.getpFiles().get(i).getPfIncludeDirectories().size(); j++) {
                    if (p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("/")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("C:")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("c:")) {
                        bw.write("-I" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    } else {
                        bw.write("-I" + p.getBaseDirectory() + "/" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    }
                    bw.write(" ");
                }
                bw.write(" -c " + p.getpFiles().get(i).getPfFileName() + " >> " + COMP_OUT_REP_WIN + " 2>&1");
                bw.newLine();
                bw.write(")");
                bw.newLine();
            }
            bw.write("del /F /Q COMP.running");
            bw.newLine();
            bw.newLine();
            bw.flush();
            bw.close();
        } else {
            String fileName = p.getBaseDirectory() + "/" + p.getProjectName() + "_comp.sh";
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(BIN_BASH_UNX);
            bw.newLine();
            bw.write("#  COMP launch script for project " + p.getProjectName());
            bw.newLine();
            bw.write(GENERATED_BY_UNX + LocalDateTime.now().format(SAFacilitator.getFormatter()));
            bw.newLine();
            bw.write(COPYRIGHT_UNX + LocalDate.now().getYear() + " - " + Strings.SPAZIOIT_WWW);
            bw.newLine();
            bw.newLine();
            bw.write("cd " + p.getBaseDirectory());
            bw.newLine();
            bw.write("rm -f " + COMP_OUT_REP_UNX);
            bw.newLine();
            bw.write("echo COMP running > COMP.running");
            bw.newLine();
            for (int i = 0; i < p.getpFiles().size(); i++) {
                bw.write("if [ -f COMP.running ]; then");
                bw.newLine();
                bw.write(p.getpFiles().get(i).getPfOriginalBuilder() + " ");
                for (int j = 0; j < p.getpFiles().get(i).getPfDefines().size(); j++) {
                    bw.write(p.getpFiles().get(i).getPfDefines().get(j).replace("\"", "\\\""));
                    bw.write(" ");
                }
                for (int j = 0; j < p.getpFiles().get(i).getPfAdditionalArguments().size(); j++) {
                    bw.write(p.getpFiles().get(i).getPfAdditionalArguments().get(j).replace("\"", "\\\""));
                    bw.write(" ");
                }
                for (int j = 0; j < p.getpFiles().get(i).getPfIncludeDirectories().size(); j++) {
                    if (p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("/")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("C:")
                            || p.getpFiles().get(i).getPfIncludeDirectories().get(j).startsWith("c:")) {
                        bw.write("-I" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    } else {
                        bw.write("-I" + p.getBaseDirectory() + "/" + p.getpFiles().get(i).getPfIncludeDirectories().get(j));
                    }
                    bw.write(" ");
                }
                bw.write(" -c " + p.getpFiles().get(i).getPfFileName() + " >> " + COMP_OUT_REP_UNX + " 2>&1");
                bw.newLine();
                bw.write("fi");
                bw.newLine();
            }
            bw.write("rm -f COMP.running");
            bw.newLine();
            bw.newLine();
            bw.flush();
            bw.close();
        }
        CommonFunctions.printLogMessage("COMP prepared.");
    }

    /**
     * @throws Exception in case of application error execute the various
     * analyzers
     */
    public void executeAnalyzers() throws Exception {
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        List<String> myList = p.getActiveAnalyzers();
        if (myList == null || myList.isEmpty()) {
            throw new Exception(Strings.ACTIVE_ANALYZERS_LIST_IS_EMPTY);
        }
        if ((SAFacilitator.isGuiEnabled()) && (myList.size() != 1) && (!p.getPreProcessingEnabled())) {
            throw new Exception("Only one analyzer at a time can be launched from the GUI!");
        }
        if (myList.contains(Strings.PC_LINT)) {
            if (!p.getPreProcessingEnabled()) {
                executePcLint();
            }
        }
        if (myList.contains(Strings.CPPCHECK)) {
            if (!p.getPreProcessingEnabled()) {
                executeCppcheck();
            }
        }
        if (myList.contains(Strings.CLANG_SA)) {
            executeClangSa();
        }
        if (myList.contains(Strings.CLANG_TIDY)) {
            if (!p.getPreProcessingEnabled()) {
                executeClangTidy();
            }
        }
        if (myList.contains(Strings.COMP)) {
            if (!p.getPreProcessingEnabled()) {
                executeComp();
            }
        }
    }

    /**
     * @throws Exception in case of application error execute PC-Lint
     */
    void executePcLint() throws Exception {
        CommonFunctions.printLogMessage("Executing PC-Lint...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String commandLine = null;
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            commandLine = p.getBaseDirectory() + "/run_pclint.bat";
        } else {
            commandLine = Strings.BASH + p.getBaseDirectory() + "/run_pclint.sh";

        }
        FileUtils.forceMkdir(new File(p.getBaseDirectory() + "/" + PCLINT_OUT_DIR));
        if (SAFacilitator.isGuiEnabled()) {
            MainFrame.getStopRunningMenuItem().setText("Stop PC-lint");
            MainFrame.getStopRunningMenuItem().setDisable(false);
        }
        executor = new Executor(commandLine, "PC-Lint executed.", true);
        executor.setPriority(Thread.MAX_PRIORITY);
        executor.start();
        if (!SAFacilitator.isGuiEnabled()) {
            executor.join();
        }
    }

    /**
     * @throws Exception in case of application error prepare Cppcheck
     */
    void executeCppcheck() throws Exception {
        CommonFunctions.printLogMessage("Executing Cppcheck...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String commandLine = null;
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            commandLine = p.getBaseDirectory() + "/run_cppcheck.bat";
        } else {
            commandLine = Strings.BASH + p.getBaseDirectory() + "/run_cppcheck.sh";
        }
        FileUtils.forceMkdir(new File(p.getBaseDirectory() + "/" + CPPCHECK_OUT_DIR));
        cppcheckBuildDir = p.getProjectName() + "-cppcheck-build-dir";
        FileUtils.forceMkdir(new File(p.getBaseDirectory() + "/" + cppcheckBuildDir));
        FileUtils.cleanDirectory(new File(p.getBaseDirectory() + "/" + cppcheckBuildDir));
        if (SAFacilitator.isGuiEnabled()) {
            MainFrame.getStopRunningMenuItem().setText("Stop Cppcheck");
            MainFrame.getStopRunningMenuItem().setDisable(false);
        }
        executor = new Executor(commandLine, "Cppcheck executed.", true);
        executor.setPriority(Thread.MAX_PRIORITY);
        executor.start();
        if (!SAFacilitator.isGuiEnabled()) {
            executor.join();
        }
    }

    /**
     * @throws Exception in case of application error execute Clang-SA
     */
    void executeClangSa() throws Exception {
        CommonFunctions.printLogMessage("Executing Clang-SA...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String commandLine = null;
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            if (!p.getPreProcessingEnabled()) {
                commandLine = p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_WIN;
            } else {
                commandLine = p.getExplodedDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_WIN;
            }
        } else {
            if (!p.getPreProcessingEnabled()) {
                commandLine = Strings.BASH + p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_UNX;
            } else {
                commandLine = Strings.BASH + p.getExplodedDirectory() + "/" + p.getProjectName() + CLANG_SA_SUFF_UNX;

            }
        }
        if (SAFacilitator.isGuiEnabled()) {
            MainFrame.getStopRunningMenuItem().setText("Stop Clang-SA");
            MainFrame.getStopRunningMenuItem().setDisable(false);
        }
        executor = new Executor(commandLine, "Clang-SA executed.", true);
        executor.setPriority(Thread.MAX_PRIORITY);
        executor.start();
        if (!SAFacilitator.isGuiEnabled()) {
            executor.join();
        }
    }

    /**
     * @throws Exception in case of application error execute Clang-Tidy
     */
    void executeClangTidy() throws Exception {
        CommonFunctions.printLogMessage("Executing Clang-Tidy...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String commandLine = null;
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            commandLine = p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_TIDY_SUFF_WIN;
        } else {
            commandLine = Strings.BASH + p.getBaseDirectory() + "/" + p.getProjectName() + CLANG_TIDY_SUFF_UNX;
        }
        FileUtils.forceMkdir(new File(p.getBaseDirectory() + "/" + CLANGTIDY_OUT_DIR));
        FileUtils.deleteQuietly(new File(p.getBaseDirectory() + "/" + CLANGTIDY_OUT_REP_UNX));
        if (SAFacilitator.isGuiEnabled()) {
            MainFrame.getStopRunningMenuItem().setText("Stop Clang-Tidy");
            MainFrame.getStopRunningMenuItem().setDisable(false);
        }
        executor = new Executor(commandLine, "Clang-Tidy executed.", true);
        executor.setPriority(Thread.MAX_PRIORITY);
        executor.start();
        if (!SAFacilitator.isGuiEnabled()) {
            executor.join();
        }
    }

    /**
     * @throws Exception in case of application error execute COMP
     */
    void executeComp() throws Exception {
        CommonFunctions.printLogMessage("Executing COMP...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String commandLine = null;
        if (System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            commandLine = p.getBaseDirectory() + "/" + p.getProjectName() + "_comp.bat";
        } else {
            commandLine = Strings.BASH + p.getBaseDirectory() + "/" + p.getProjectName() + "_comp.sh";
        }
        FileUtils.forceMkdir(new File(p.getBaseDirectory() + "/" + COMP_OUT_DIR));
        FileUtils.deleteQuietly(new File(p.getBaseDirectory() + "/" + COMP_OUT_REP_UNX));
        if (SAFacilitator.isGuiEnabled()) {
            MainFrame.getStopRunningMenuItem().setText("Stop COMP");
            MainFrame.getStopRunningMenuItem().setDisable(false);
        }
        executor = new Executor(commandLine, "COMP executed.", true);
        executor.setPriority(Thread.MAX_PRIORITY);
        executor.start();
        if (!SAFacilitator.isGuiEnabled()) {
            executor.join();
        }
    }

    /**
     * @throws Exception in case of application error post-process the various
     * analyzers
     */
    public void postProcessAnalyzers() throws Exception {
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        List<String> myList = p.getActiveAnalyzers();
        if (myList == null || myList.isEmpty()) {
            throw new Exception(Strings.ACTIVE_ANALYZERS_LIST_IS_EMPTY);
        }
        if (myList.contains(Strings.PC_LINT)) {
            if (!p.getPreProcessingEnabled()) {
                postProcessPcLint();
            }
        }
        if (myList.contains(Strings.CPPCHECK)) {
            if (!p.getPreProcessingEnabled()) {
                postProcessCppcheck();
            }
        }
        if (myList.contains(Strings.CLANG_SA)) {
            postProcessClangSa();
        }
        if (myList.contains(Strings.CLANG_TIDY)) {
            if (!p.getPreProcessingEnabled()) {
                postProcessClangTidy();
            }
        }
        if (myList.contains(Strings.COMP)) {
            if (!p.getPreProcessingEnabled()) {
                postProcessComp();
            }
        }
    }

    /**
     * @throws Exception in case of application error post-process PC-Lint
     */
    void postProcessPcLint() throws Exception {
        CommonFunctions.printLogMessage("Post processing PC-Lint...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        if (!System.getProperty(Strings.OS_NAME).toLowerCase().startsWith(Strings.WINDOWS)) {
            FileReader fr = new FileReader(PCLINT_OUT_REP_UNX);
            FileWriter fw = new FileWriter(PCLINT_OUT_REP_UNX + ".tmp");
            BufferedReader br = new BufferedReader(fr);
            BufferedWriter bw = new BufferedWriter(fw);
            String line = br.readLine();
            while (line != null) {
                bw.write(line.replace("\\", "/"));
                bw.newLine();
                line = br.readLine();
            }
            bw.close();
            br.close();
            FileUtils.deleteQuietly(new File(PCLINT_OUT_REP_UNX));
            FileUtils.moveFile(new File(PCLINT_OUT_REP_UNX + ".tmp"), new File(PCLINT_OUT_REP_UNX ));
        }
        CommonFunctions.printLogMessage("PC-Lint post processed.");
    }

    /**
     * @throws Exception in case of application error post-process Cppcheck
     */
    void postProcessCppcheck() throws Exception {
        CommonFunctions.printLogMessage("Post processing Cppcheck...");
        // Nothing to be done
        CommonFunctions.printLogMessage("Cppcheck post processed.");
    }

    /**
     * @throws Exception in case of application error post-process Clang-SA
     */
    void postProcessClangSa() throws Exception {
        CommonFunctions.printLogMessage("Post processing Clang-SA...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String extensions[] = new String[1];
        extensions[0] = "plist";
        File baseDirectory = null;
        if (!p.getPreProcessingEnabled()) {
            baseDirectory = new File(p.getBaseDirectory());
        } else {
            baseDirectory = new File(p.getExplodedDirectory());
        }
        File directory = null;
        if (!p.getPreProcessingEnabled()) {
            directory = new File(p.getBaseDirectory() + "/" + CLANGSA_OUT_DIR);
        } else {
            directory = new File(p.getExplodedDirectory() + "/" + CLANGSA_OUT_DIR);
        }
        FileUtils.forceMkdir(directory);
        for (File file : FileUtils.listFiles(directory, extensions, true)) {
            FileUtils.deleteQuietly(file);
        }
        for (File file : FileUtils.listFiles(baseDirectory, extensions, false)) {
            FileUtils.moveFileToDirectory(file, directory, false);
        }
        CommonFunctions.printLogMessage("Clang-SA post processed.");
    }

    public void replaceString(String oldstring, String newstring, File in, File out) throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader(in));
        PrintWriter writer = new PrintWriter(new FileWriter(out));
        String line = null;
        while ((line = reader.readLine()) != null) {
            writer.println(line.replace(oldstring, newstring));
        }
        reader.close();
        writer.close();
    }

    /**
     * @throws Exception in case of application error post-process Clang-Tidy
     */
    void postProcessClangTidy() throws Exception {
        CommonFunctions.printLogMessage("Post processing Clang-Tidy...");
        // Nothing to be done
        CommonFunctions.printLogMessage("Clang-Tidy post processed.");
    }

    /**
     * @throws Exception in case of application error post-process COMP
     */
    void postProcessComp() throws Exception {
        CommonFunctions.printLogMessage("Post processing COMP...");
        Project p = safacilitator.getCurrentProject();
        if (p == null) {
            throw new Exception(Strings.CURRENT_PROJECT_IS_NULL);
        }
        String extensions[] = new String[2];
        extensions[0] = "o";
        extensions[1] = "obj";
        File baseDirectory = new File(p.getBaseDirectory());
        for (File file : FileUtils.listFiles(baseDirectory, extensions, true)) {
            FileUtils.deleteQuietly(file);
        }
        CommonFunctions.printLogMessage("COMP post processed.");
    }
}
